### ISSUE TITLE
The sort_by filter only works with arrays

### ISSUE THREAD

**Issue by stefjakobs** [BesrourMS/clean-blog#1]
Hello,

I get the following error with picocms 1.0.3, PHP 5.4.45-0+deb7u3, lighttpd 1.4.31-4+deb7u4 and your current theme:

`2016-06-21 23:04:34: (mod_fastcgi.c.2676) FastCGI-stderr: PHP message: PHP Fatal error:  Uncaught exception 'Twig_Error_Runtime' with message 'The sort_by filter only works with arrays or "Traversable", got "NULL" in "index.twig" at line 82' in /var/www/picocms/blog/lib/PicoTwigExtension.php:147
Stack trace:
#0 /var/www/picocms/blog/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code(183): PicoTwigExtension->sortByFilter(NULL, 'time')
#1 /var/www/picocms/blog/vendor/twig/twig/lib/Twig/Template.php(381): __TwigTemplate_eff2f6456aeae6fa80fb2909f605617fd837cd8130e7b2e3acb8eb9b270e1bd1->doDisplay(Array, Array)
#2 /var/www/picocms/blog/vendor/twig/twig/lib/Twig/Template.php(355): Twig_Template->displayWithErrorHandling(Array, Array)
#3 /var/www/picocms/blog/vendor/twig/twig/lib/Twig/Template.php(366): Twig_Template->display(Array)
#4 /var/www/picocms/blog/vendor/twig/twig/lib/Twig/Environment.php(347): Twig_Template->render(Array)
#5 /var/www/picocms/blog/lib/Pico.php(368): Twig_Environment->render('index.twig', Array)
#6 /var/www/picocms/blog/index.php(20...

`

**Comment by BesrourMS** [comment]
Please check the installation of Pico Pagination Plugin, it is required for this theme.

**Comment by MartijnDevNull** [comment]
I have the pagination plugin installed but it's still giving this error. What else could be wrong?

**Comment by LucaTony** [comment]
@MartijnDevNull @stefjakobs I had the same error. Try adding also the content files from ``content-sample`` . My guess is that the twig-array need at least one post.
