### ISSUE TITLE
Is the Demo link the Pico CMS version?

### ISSUE THREAD

**Issue by rollanders** [BesrourMS/clean-blog#10]
Thanks a lot for great work. But I get confused. After having installed the PicoCMS theme I cannot get it work like in your demo. I first thought the demo link is to the HTML5 version, but after looking into the index.twig I think I understand that there are some things in there that needs to be mended to.
I guess some information about that would be helpful

**Comment by rollanders** [comment]
I was wrong.

**Comment by claudiofontana** [comment]
Me too i'm facing with same problem. How do you solved?
