### ISSUE TITLE
Theme not showing posts, only post list

### ISSUE THREAD

**Issue by iagovar** [BesrourMS/clean-blog#8]
Hi, I installed this theme and the pagination plugin, but It isn't working.

If you click a post like http://iagovar.com/pico/cierre-foros-vogue-histeria-social it just shows a post list, not the post itself. It works with the default theme.

**Comment by Heartade** [comment]
Did you set the page template to "post"?

**Comment by gelavat** [comment]
> Did you set the page template to "post"?

What do you mean by this exactly, how can I set the page template to "post", in what file?

**Comment by BesrourMS** [comment]
Hi @gelavat, please check the file post.md 
https://github.com/BesrourMS/clean-blog/blob/master/content-sample/post.md

**Comment by gelavat** [comment]
Thank you very much, now it is clear how to do a post md file properly.
Great!
